version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: tpdb_postgres
    environment:
      POSTGRES_USER: tpdb_user
      POSTGRES_PASSWORD: tpdb_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tpdb_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: tpdb_keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: tpdb_user
      KC_DB_PASSWORD: tpdb_pass
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./keycloak/realms/tpdb-realm.json:/opt/keycloak/data/import/tpdb-realm.json:ro

volumes:
  postgres_data:
